version: '3'

services:

  mysql-db:
    container_name: mysql-db
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
    ports:
      - "3306:3306"
    networks:
      - app-network

  demo-app:
    container_name: demo-app
    build: ./backend
    image: "demo-app:latest"
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db
    networks:
      - app-network

  frontend-app:
    container_name: frontend-app
    build: ./frontend
    image: "frontend-app:latest"
    environment:
      - HOST=0.0.0.0
    ports:
      - "8080:8080"
    depends_on:
      - demo-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge